// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8fuwvUrwakwnWxGLejH52HhoPwVeVuWg',
    appId: '1:285951515003:web:ffb71f2113d92177c085de',
    messagingSenderId: '285951515003',
    projectId: 'h2overview-iot',
    authDomain: 'h2overview-iot.firebaseapp.com',
    databaseURL: 'https://h2overview-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'h2overview-iot.appspot.com',
    measurementId: 'G-925PGX15PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEEqPBkK5rkvByNQMzs6isQGwO240doyM',
    appId: '1:285951515003:android:941418a13f07e2eec085de',
    messagingSenderId: '285951515003',
    projectId: 'h2overview-iot',
    databaseURL: 'https://h2overview-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'h2overview-iot.appspot.com',
  );

}